skycoin/skycoin-explorer

.editorconfig
README.md
explorer.go

Rewritten from https://github.com/skycoin/skycoin/blob/develop/cmd/explorer/explorer.go

Add explorer.go

---

src/app/services/api/api.service.ts

*Note:* Did not recompile dist
Was not able to check that `getCoinSupply()` works now, the api endpoint should be correct but maybe it isn't updating the page

Fix api service routes

---

src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/transaction-detail/transaction-detail.component.html

Small changes for showing human readable timestamps on the transactions page and on the address page. Issues involved: https://github.com/skycoin/skycoin-explorer/issues/70 https://github.com/skycoin/skycoin-explorer/issues/64 https://github.com/skycoin/skycoin/issues/753

human readable timestamps

---

explorer.go

no similar docs found in README.md
https://github.com/skycoin/skycoin-explorer/issues/50

richlist and addresscount

---

src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/address-detail/address-detail.component.scss
src/app/components/pages/address-detail/address-detail.component.ts

Now it is possible to click on the transaction links on the address page. Issue involved: https://github.com/skycoin/skycoin/issues/755

Transaction link clickable (address page)

---

.gitignore
.travis.yml
Makefile

Adds `make format`, `make check`, `make lint`

Make format

---

explorer.go

Fixes https://github.com/skycoin/skycoin-explorer/issues/98

Update coinSupply replacing getEffectiveOutputs

---

explorer.go

Changes requested in https://github.com/skycoin/skycoin-explorer/issues/94 and https://github.com/skycoin/skycoin-explorer/issues/102
As is well known, an updated node with https://github.com/skycoin/skycoin/pull/869 must be used for it to work.
It does not solve https://github.com/skycoin/skycoin-explorer/issues/101

Update /coinSupply docs

---

explorer.go

Fixes https://github.com/skycoin/skycoin-explorer/issues/109

"seq" query arg

---

src/app/app.datatypes.ts
src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/address-detail/address-detail.component.scss
src/app/components/pages/address-detail/address-detail.component.ts
src/app/services/explorer/explorer.service.ts

Solves https://github.com/skycoin/skycoin-explorer/issues/113

Show balance over time

---

src/app/components/pages/blocks/block.ts
src/app/components/pages/blocks/blocks.component.html
src/app/components/pages/blocks/blocks.component.ts

Fixes https://github.com/skycoin/skycoin-explorer/issues/101

Show coinhour supply

---

Dockerfile
README.md

Resolves issue #110 by adding the Dockerfile to create and deploy Docker images.

[docker] refs #110 Adds Dockerfile for deployment.

---

explorer.go

Solves https://github.com/skycoin/skycoin-explorer/issues/142

/transactions endpoint

---

src/app/components/layout/footer/footer.component.html
src/app/components/layout/header/header.component.html

@gz-c @samuelvisscher this fixes site's header and footer to match [main site](http://skycoin.net)

update header to match main site

---

e2e/unspent-outputs/unspent-outputs.e2e-spec.ts
e2e/unspent-outputs/unspent-outputs.po.ts
src/app/app.module.ts
src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/unspent-outputs/unspent-outputs.component.html
src/app/components/pages/unspent-outputs/unspent-outputs.component.ts
src/app/components/pages/unspent-outputs/unspent-outputs.spec.ts
src/styles.scss

Solves https://github.com/skycoin/skycoin-explorer/issues/158
Link added to the address page:
The list looks like this:
This pr also have e2e test for the page. However, the tests are similar to the ones on https://github.com/skycoin/skycoin-explorer/pull/145 and https://github.com/skycoin/skycoin-explorer/pull/146, so there room for future improvements.

Unspent outputs page

---

src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/address-detail/address-detail.component.ts

Solves https://github.com/skycoin/skycoin-explorer/issues/157
The total amount received is displayed in this way:
The spacing problems will be solved in another pr.

Show total received

---

src/app/components/pages/block-details/block-details.component.html
src/app/services/explorer/explorer.service.ts

At this moment it is not possible to see the genesis block details, the explorer stays loading indefinitely. This pr solved that error.

Fix genesis block details

---

explorer.go

Fixes #193 
It is possible to continue connecting to the node without the `/api/v1/` prefix, by using `-use-unversioned-api `

Use /api/v1/ prefixed endpoints

---

src/app/components/layout/footer/footer.component.html

https://github.com/skycoin/skycoin.net/issues/464

update Facebook URL

---

src/app/components/layout/coins-formatter/coins-formatter.component.ts

This PR solves an error that made the amounts greater than 999,999 to be incorrectly displayed.

Fix CoinsFormatterComponent

---

explorer.go

Updates explorer.go with the changes made in https://github.com/skycoin/skycoin/pull/1800

Update the /api/health endpoint

---

package-lock.json
package.json
src/app/app.datatypes.ts
src/app/components/layout/transaction-info/transaction-info.component.html
src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/address-detail/address-detail.component.ts
src/app/components/pages/unspent-outputs/unspent-outputs.component.html
src/app/components/pages/unspent-outputs/unspent-outputs.component.ts
src/app/pipes/transactions-value.pipe.ts
src/app/services/explorer/explorer.service.ts

Now the code uses bignumber.js to perform the calculations that involve coins and hours, to avoid problems with how JavaScript operates with numbers

Use bignumber.js

---

explorer.go

Fixes:
#259 
Changes:
- Add `/api/coinmarketcap` endpoint

Add /api/coinmarketcap endpoint

---

dist/assets/i18n/en.json
e2e/blocks/blocks.e2e-spec.ts
e2e/blocks/blocks.po.ts
src/app/components/layout/footer/footer.component.html
src/app/components/layout/header/header.component.html
src/app/components/pages/blocks/blocks.component.html
src/assets/i18n/en.json

- Added Explorer API link to the Explorer page
- Updated header Explorer API link
- Updated footer Explorer API link

Explorer API link

---

explorer.go
src/app/app.datatypes.ts
src/app/services/api/api.service.ts
src/app/services/explorer/explorer.service.ts

Fixes #269 
@Senyoret1 The structure of the response has changed, so the frontend needs more modification to extract the data correctly.  Compare:
http://127.0.0.1:6420/api/v1/explorer/address?address=DFFfL65HUtfMGH8LyME3y14Qaoz4zY6cYy
```json
[
{
"status": {
"confirmed": true,
"unconfirmed": false,
"height": 1,
"block_seq": 90874
},
"timestamp": 1547275277,
"length": 220,
"type": 0,
"txid": "ae38a85422d0a5224a977b88a98ea771c25bbb9bbb54f2b2a20b46473418416b",
"inner_hash": "ce25c36b9f15308d373ac501f3c2f0b0d02d316e0013befab3d4cc2b32e874c1",
"fee": 78766,
"sigs": [
"d7be9ef6918f263d4986275e9538ed40eab97b079b04d1873191b9a9a0e044a35fdd93e76ec0d13edaf90f1bb8af9d28ebbe6c99a4e896bae26b20cc3a6b04ae01"
],
"inputs": [
{
"uxid": "10254717c97dc7785a06a649d469a1884cddfc7b3a0312d297ca34b7bd726aff", …
```

Switch from /explorer/address to /transactions

---

src/app/components/pages/unspent-outputs/unspent-outputs.component.html
src/styles.scss

Changes:
- Fixes a problem with the margins in the address details page:

Fix the tx details margin

---

src/app/app.component.ts
src/app/components/pages/address-detail/address-detail.component.html
src/app/components/pages/address-detail/address-detail.component.ts
src/app/components/pages/block-details/block-details.component.html
src/app/components/pages/block-details/block-details.component.ts
src/app/components/pages/blocks/blocks.component.html
src/app/components/pages/blocks/blocks.component.ts
src/app/components/pages/richlist/richlist.component.html
src/app/components/pages/richlist/richlist.component.ts
src/app/components/pages/transaction-detail/transaction-detail.component.html
src/app/components/pages/transaction-detail/transaction-detail.component.ts
src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.html
src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.ts
src/app/components/pages/unspent-outputs/unspent-outputs.component.html
src/app/components/pages/unspent-outputs/unspent-outputs.component.ts

Some text were not being updated automatically after changing the language. This PR solves that problem.

Improvements for the code that manage the translations
