skycoin/skycoin-explorer

- explorer.go
* Default the host:port to `127.0.0.1:8001`
* Rename `SKYCOIN_HOST` envvar to `SKYCOIN_ADDR`
* Rename `SKYCOIN_EXPLORER_HOST` envvar to `EXPLORER_HOST`
* Configurable skycoin node proxy endpoints
* Better logging
* `/api/currentBalance` endpoint's query arg `address` renamed to `addrs` to match the skycoin node API
* `/api/hello` renamed to `/api/outputs`.  This endpoint might be unnecessary altogether. `/api/currentBalance` also calls the skycoin API's `/outputs` endpoint internally, albeit with a query arg.
> Refactoring explorer.go

- README.md
- explorer.go
Also removes `/api/outputs` since it was a duplicate of `/api/currentBalance`, but maybe it should be the other way around
> Explorer API docs

- explorer.go
Remove documentation of deprecated `/explorer/getEffectiveOutputs` fields.
The deprecated fields still exist, just removing docs of them
> Update coinSupply docs

- src/app/components/pages/address-detail/address-detail.component.ts
With this change, the transactions on the address screen are sorted starting with the most recent and ending with the oldest one. The change was made by inverting the order of the transactions, because the api of the nodes returns the list starting with the oldest transaction and endind with the newest. The new code was placed directly inside the code of the address screen and not inside the code that makes the connection to the api, so any other screen (existing or future) calling ExplorerService.getTransactions will receive the results with the default sorting returnen by the nodes (this is to avoid inconsistencies that may generate confusion in the future). Issues involved: https://github.com/skycoin/skycoin-explorer/issues/69 https://github.com/skycoin/skycoin/issues/752
> Sort transactions newest to oldest

- README.md
Info about `make format`, `make install-linters` and `make lint` (added in https://github.com/skycoin/skycoin-explorer/pull/97)
> Add formatting info to README.md

- explorer.go
- src/app/app.datatypes.ts
- src/app/components/pages/address-detail/address-detail.component.html
The changes made in https://github.com/skycoin/skycoin/pull/869 were added to explorer.go. The new data was used to show the amount of coins going in or out during a transaction, on the address page. The amount of coins is shown as follows:
> Show the amount of coins going in or out during a transaction

- src/app/components/pages/address-detail/address-detail.component.html
- src/app/components/pages/block-details/block-details.component.html
- src/app/components/pages/blocks/blocks.component.html
- src/app/components/pages/blocks/blocks.component.scss
- src/app/components/pages/transaction-detail/transaction-detail.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.html
- src/styles.scss
Solves https://github.com/skycoin/skycoin-explorer/issues/81 . The modifications on this pr are not only to fix the problems while selecting the addresses and dates, but also for making easier to select most of the important data. This includes the data of the blockchain in the initial screen, the details of the transactions, etc. However, selecting the text of the links by double clicking can still be a bit complicated, so it may be good to add buttons for copying.
The changes were a bit long due to differences in the operation of the different explorers. The changes were tested in recent versions of Chrome, Firefox and Edge.
> Fix double click selection

- src/app/app.datatypes.ts
- src/app/components/pages/address-detail/address-detail.component.html
- src/app/components/pages/block-details/block-details.component.html
- src/app/components/pages/transaction-detail/transaction-detail.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.ts
- src/app/services/explorer/explorer.service.ts
Solves https://github.com/skycoin/skycoin-explorer/issues/111 and https://github.com/skycoin/skycoin-explorer/issues/114 .
The addresses are obtained with a workaround already present in the explorer (except while quering addresses, the node's api does not return addresses of the inputs, only the hashes), so the performance remains the same as before. However, the procedure will be more efficient with the changes indicated in the two issues solved by this pr.
Now transactions look like this:
> Show the input addresses

- explorer.go
Solves https://github.com/skycoin/skycoin-explorer/issues/49
It is a single line of code that sends to stdout all messages sent by `log`, so the change works automatically without changing the rest of the code. However, if you find it better replace the direct calls to the `log` package with a new log object with a name like `stdoutLog` (for readability reasons), it can be done.
> Send logs to stdout

- src/app/services/explorer/explorer.service.ts
This pr solves an error ( reported in https://github.com/skycoin/skycoin-explorer/issues/154 ) that caused the transaction page to show "loading" infinitely if there were no unconfirmed transactions (if there were, the page worked correctly).
> Fix unconfirmed txs page

- src/app/components/pages/blocks/blocks.component.html
- src/app/components/pages/richlist/richlist.component.html
- src/assets/scss/_variables.scss
- src/styles.scss
This pr affects the block lists and the rich list.
The first change is a simple fix for a problem with the text selection that happened when double-clicking on the list header (it was not resolved in talll to avoid conflicts with others pr). 
The other change is that the rows of the tables are highlighted when the mouse is over them. This is to improve the usability, since all the other links are underlined when the mouse is over them, while the rows of the list do not have any visual clue indicating that they are clickable links.
> Small improvements for the lists

- src/app/app.module.ts
- src/app/components/pages/address-detail/address-detail.component.html
- src/app/components/pages/address-detail/address-detail.component.ts
- src/app/components/pages/blocks/blocks.component.scss
- src/styles.scss
This solves part of https://github.com/skycoin/skycoin-explorer/issues/89
As indicated in the issue, the address screen takes a long time to load if the address has many transactions. The slowness is due to two things: the need to download all the transactions at once and the large number of elements that must be added to the DOM.
Since no changes have been made to the api or the node, this pr does not solve the first problem. However, paging was implemented as on the block list, and now only 25 transactions are displayed at the same time, which eliminates the second problem. The efficiency in the use of the network remains the same, since the list of transactions is requested to the server only once, regardless of whether the user uses the paging control.
After implementing the necessary …
> Transactions pagination

- src/styles.scss
Solve this small problem in the address page:
With the change, it looks like this:
> Spacing fix

- explorer.go
Adds the /balance endpoint, which can be useful for the address screen. At this moment the balance of the addresses is calculated with the api endpoint which returns all the unspent outputs, the /balance endpoint returns much less data, so using it would be more efficient.
> Add /balance endpoint

- src/app/components/layout/copy-button/copy-button.component.ts
The copy button was preventing production builds to be correctly made (using `make build-ng`), dev buils had no problems (the ones made with `ng build`). This pr fixes the problem.
> Small fix for CopyButtonComponent

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/app.reuse-strategy.ts
- src/app/components/pages/address-detail/address-detail.component.ts
Solves https://github.com/skycoin/skycoin-explorer/issues/163
To solve the second point of the issue this pr changes the way the Angular router works. Normally, when navigating to the same URL in which the user is already located, Angular reuses the page component. If the URL is different, the router creates a new component. With this pr the router stops working in that way, now always creates a new component, regardless of whether the URL is the same and only changed the parameters.
However, an exception was placed. The address page continues to work as before. This allows to clean the screen directly in the AddressDetailComponent code and thus avoid reloading the data from the server every time a change is made in the paging, which would be very slow when the addresses have many …
> Fix the scroll positioning

- e2e/transaction-detail/transaction-detail.e2e-spec.ts
https://github.com/skycoin/skycoin-explorer/pull/159 and https://github.com/skycoin/skycoin-explorer/pull/160 added a new row each to the address details table, in the address page. As a result, an e2e test fails. The correction is in this pr because the changes that make the test fail are in 2 prs and not 1....
> Small e2e fix

- e2e/address-detail/address-detail.e2e-spec.ts
- e2e/block-details/block-details.e2e-spec.ts
- e2e/transaction-detail/transaction-detail.e2e-spec.ts
- e2e/unconfirmed-transactions/unconfirmed-transactions.e2e-spec.ts
- explorer.go
- src/app/app.datatypes.ts
- src/app/components/pages/block-details/block-details.component.html
- src/app/components/pages/transaction-detail/transaction-detail.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.ts
- src/app/services/api/api.service.ts
Solves https://github.com/skycoin/skycoin-explorer/issues/135
Change in the block details page:
Change in the transaction page:
Change in the unconfirmed transactions page:
This pr also includes fixes for the e2e tests.
> Display block and transaction size

- src/app/components/layout/copy-button/copy-button.component.scss
After updating Font Awesome, some copy buttons changed their appearance from this:
To this:
This pr makes all copy buttons look like the first image, to maintain consistency.
> Fix copy button style

- src/app/components/layout/qr-code/qr-code.component.ts
This pr makes the qr codes compatible with Bip 21, the format used by the wallet from this pr: https://github.com/skycoin/skycoin/pull/1185
> Bip21 compatible qr codes

- CUSTOMIZATION.md
- README.md
- src/app/app.config.ts
- src/app/components/layout/qr-code/qr-code.component.ts
Improvement suggested  in https://github.com/skycoin/skycoin-explorer/pull/186#issuecomment-385856522
With this pr it is now possible to configure the prefix of the addresses in the qr codes. This makes it easier to configure the use of BIP21 while customizing the explorer.
This pr also includes the corresponding indications in CUSTOMIZATION.md, so it would be good if the wording is reviewed.
> Configurable qr codes

- .snyk
- package.json
Similar to https://github.com/skycoin/skycoin-explorer/pull/175, but keeps jasmine-core version 2 to avoid problems. The explorer and the e2e tests continue to work after updating the packages.
> [WIP] Snyk update

- e2e/block-details/block-details.e2e-spec.ts
- e2e/block-details/block-details.po.ts
- src/app/components/pages/block-details/block-details.component.html
- src/app/components/pages/block-details/block-details.component.scss
- src/app/components/pages/block-details/block-details.component.ts
- src/assets/i18n/en.json
Fixes #201 
This pr adds the "Previous block" and "Next block" buttons to the block details page and e2e test for them. The buttons are similar to those on the website, although not exactly the same. They look like this:
Big screen:
Small screen:
During the implementation I created a similar but more subtle desing. Personally I like it more, but it is not so consistent with the design of the website. It looks like this:
Big screen:
Small screen:
If you prefer the softer design, I can make the change without much trouble.
> Add next/prev block buttons to block page

- e2e/transaction-detail/transaction-detail.po.ts
- src/app/components/pages/transaction-detail/transaction-detail.component.html
Fixes #204 
- Now the block number works as a link.
> Link to block page from transaction page

- e2e/address-detail/address-detail.po.ts
- e2e/blocks/blocks.po.ts
- src/app/app.module.ts
- src/app/components/layout/coins-formatter/coins-formatter.component.html
- src/app/components/layout/coins-formatter/coins-formatter.component.scss
- src/app/components/layout/coins-formatter/coins-formatter.component.spec.ts
- src/app/components/layout/coins-formatter/coins-formatter.component.ts
- src/app/components/layout/date-formatter/date-formatter.component.html
- src/app/components/layout/date-formatter/date-formatter.component.scss
- src/app/components/layout/date-formatter/date-formatter.component.spec.ts
- src/app/components/layout/date-formatter/date-formatter.component.ts
- src/app/components/pages/address-detail/address-detail.component.html
- src/app/components/pages/block-details/block-details.component.html
- src/app/components/pages/blocks/blocks.component.html
- src/app/components/pages/blocks/blocks.component.scss
- src/app/components/pages/richlist/richlist.component.html
- src/app/components/pages/transaction-detail/transaction-detail.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.html
- src/app/components/pages/unspent-outputs/unspent-outputs.component.html
- src/assets/i18n/en.json
- src/assets/scss/_variables.scss
- src/styles.scss
This PR does not change the appearance of the explorer in an important way, but it improves the readability of the data and fixes small errors.
Currently the explorer has problems showing the block page on small screens:
This PR fixes the consistency of the lines in the "stats" area and modifies the format of the dates in the table, so that them fits correctly: The PR also vertically centers the content of the tables, to improve the appearance on small screens:
Also, currently the amounts are difficult to read, since it is difficult to differentiate the commas from the points. The same thing happens to the dates, they are difficult to read because they contain many numbers:
This PR changes the style of the dates and the amouts, to make them easier to read:
The necessary changes to the e2e …
> Design improvements

- e2e/address-detail/address-detail.e2e-spec.ts
- e2e/address-detail/address-detail.po.ts
- src/app/app.datatypes.ts
- src/app/components/pages/address-detail/address-detail.component.html
- src/app/services/explorer/explorer.service.ts
- src/assets/i18n/en.json
- src/styles.scss
Currently, the address page shows the final balance left in the address after each transaction, but not what the initial balance was. Knowing the initial balance makes it much easier to review the transaction history if the address has many transactions. This PR adds that data.
The initial balance looks like this:
Using small screens it looks like this:
Also, this pr adapts the e2e test of the final balance and adds a new one, for the initial balance.
> Show the initial address balance

- src/app/components/pages/address-detail/address-detail.component.ts
- src/app/components/pages/block-details/block-details.component.ts
- src/app/components/pages/transaction-detail/transaction-detail.component.ts
- src/app/components/pages/unspent-outputs/unspent-outputs.component.ts
- src/assets/i18n/en.json
Currently, when searching for an item that does not exist, the explorer shows "Loading error" in several parts. For example, if you search for the details of a block that does not exist, this is displayed:
This happens in the block details, transaction, address and outputs pages.
This PR changes the message to "No data to show", a more appropriate message for the UX, since the current one may suggest that there was an error with the system:
Additionally, the message shown when looking for a block that does not exist was improved.
> Improved error messages

- CUSTOMIZATION.md
- angular.json
- src/app/app.module.ts
- src/app/components/layout/search-bar/search-bar.component.html
- src/app/components/layout/search-bar/search-bar.component.scss
- src/app/components/layout/search-bar/search-bar.component.ts
- src/app/components/pages/search/search.component.html
- src/app/components/pages/search/search.component.spec.ts
- src/app/components/pages/search/search.component.ts
- src/app/services/search/search.service.spec.ts
- src/app/services/search/search.service.ts
- src/assets/i18n/en.json
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/index.html
- src/search.dev.xml
- src/search.xml
Fixes #213 
Changes:
- This PR integrates the explorer to the browser's search functionality. In Google Chrome it is possible to search using the Omnibox and in Firefox you can add the explorer as a search engine:
- In the previous image "Test" appears after "Skycoin Explorer" because this PR includes two configurations. While using a production build, the searches are done in https://explorer.skycoin.net and the text "Test" disappears. While using a develoment build, the searches are done in http://localhost:4200 (the default URL of the test server) and the text "Test" appears.
- Added information in `CUSTOMIZATION.md` about how to edit `search.xml`, to make the search functionality work if the browser is hosted on another URL.
- The code that built the search URLs was moved from …
> fixes #213 - Improved search capabilities

- .travis.yml
Fixes #219 
Changes:
- Added golang 1.10 to travis's matrix
Does this change need to mentioned in CHANGELOG.md?
No
> [ci] fixes #219 - Travis builds for golang 1.10

- src/app/components/pages/richlist/richlist.component.scss
- src/styles.scss
Changes:
- Fix a problem that made the elements of the rich list to be underlined when the mouse is over, in Chrome.
- Fix a problem that made the small "Address" text, on the address details page, to have an incorrect color (only visible when the browser window is very small):
> Fix style problems

- explorer.go
Fixes #230 
Changes:
- Adds the `/api/health` endpoint to explorer.go. It is a proxy for the `/api/v1/health` endpoint of the node.
> Add the /api/health endpoint

- e2e/address-detail/address-detail.e2e-spec.ts
- e2e/address-detail/address-detail.po.ts
- src/app/components/pages/address-detail/address-detail.component.html
- src/app/components/pages/address-detail/address-detail.component.ts
- src/assets/i18n/en.json
Changes:
- Now the address details page shows the number of coins that have been sent from the address:
> Show total sent

- e2e/address-detail/address-detail.po.ts
- src/app/app.datatypes.ts
- src/app/components/pages/address-detail/address-detail.component.html
- src/app/components/pages/block-details/block-details.component.html
- src/app/components/pages/transaction-detail/transaction-detail.component.html
- src/app/components/pages/unconfirmed-transactions/unconfirmed-transactions.component.html
- src/assets/i18n/en.json
- src/styles.scss
Changes:
- Now the system indicates what the fee (in hours) of the transactions was. The change was done in the block details page, the transaction details page, the pending transactions page and the address details page.
- The text of the initial and final balances of the address was changed a little in the address details page, in order to make it a little clearer, because there are now values in coins and in hours. In the current version it looks like this:
> Show tx fee

- package.json
- protractor.conf.js
In this repository it is possible to execute e2e tests with both `npm run e2e` and `npm run e2e-blockchain-180`. `npm run e2e-blockchain-180` is used to run the tests in Travis, using a limited and controlled database, but that command is inconvenient to run the tests during normal development, because it involves using a node with `blockchain-180.db`, that's why `npm run e2e` exists, to be able to run the tests with a normal node.
This PR makes the configuration of `npm run e2e` to be more similar to that of `npm run e2e-blockchain-180`, to avoid some problems that occurred only when executing `npm run e2e`.
> Fix normal e2e tests

- src/app/components/layout/transaction-info/transaction-info.component.html
- src/app/components/layout/transaction-info/transaction-info.component.scss
- src/app/components/layout/transaction-info/transaction-info.component.ts
- src/assets/i18n/en.json
Continuing from https://github.com/skycoin/skycoin-explorer/pull/247#issuecomment-430507998
Changes:
Now when a transaction has too many outputs or inputs, instead of showing them in groups of 10, the user has the option to show all the elements:
As showing too many elements is an intensive task for Angular, while the processing is done, a loading message is displayed and the click events are deactivated (this is due to the fact that the waiting time could cause some users to press the link again and have an unwanted redirect just after Angular finishes processing and the browser render process is no longer busy):
As the transactions with many outputs or inputs are rare, this is a behavior that should be infrequent.
> Add the "Show all" option

- e2e/unspent-outputs/unspent-outputs.e2e-spec.ts
- e2e/unspent-outputs/unspent-outputs.po.ts
- explorer.go
- src/app/app.datatypes.ts
- src/app/components/pages/unspent-outputs/unspent-outputs.component.html
- src/app/components/pages/unspent-outputs/unspent-outputs.component.ts
- src/assets/i18n/en.json
Changes:
- The number of hours is now displayed on the unspent outputs page.
- The information about `/api/currentBalance` was updated in `explorer.go`.
- The e2e tests were updated to be compatible with the changes made.
> Show the hours on the unspent outputs page

- src/app/components/layout/transaction-info/transaction-info.component.ts
- src/app/components/pages/transaction-detail/transaction-detail.component.html
Now the txn details page shows up to 32 inputs and outputs, instead of 10
> Show more inputs/outputs on the txn details page
